import fs from 'fs';
import path from 'path';
import blogPosts from './lib/data/blogPosts';

const targetSlugs = [
  "usda-reap-grant-vs-utility-rebates",
  "sred-tax-credits-vs-cdap-canadian-founders",
  "sba-7a-loans-vs-state-grants-comparison",
  "5-best-government-loans-agriculture-tech-startups",
  "top-10-no-equity-grants-black-female-entrepreneurs",
  "7-startup-accelerators-california-free-money",
  "10-easy-to-win-local-grants-canadian-retail-stores"
];

function cleanFluff(text) {
  if (!text) return text;
  // Remove the repetitive AI words that the user complained about
  let cleaned = text
    .replace(/\b(massive|massively|localized|deeply|aggressively|highly|intensely|extremely)\s+/gi, '')
    // Run it twice to catch stacked adjectives like "massive highly localized"
    .replace(/\b(massive|massively|localized|deeply|aggressively|highly|intensely|extremely)\s+/gi, '')
    .replace(/\b(massive|massively|localized|deeply|aggressively|highly|intensely|extremely)\s+/gi, '');
  
  // Also clean up any double spaces generated by the removal
  cleaned = cleaned.replace(/ +/g, ' ');
  return cleaned;
}

const targetPosts = blogPosts.filter(p => targetSlugs.includes(p.slug));

let extractedCount = 0;

for (const post of targetPosts) {
  // Clean the content, short answer, excerpt, and FAQ
  post.content = cleanFluff(post.content);
  post.shortAnswer = cleanFluff(post.shortAnswer);
  post.excerpt = cleanFluff(post.excerpt);
  if (post.seo) {
    post.seo.metaDescription = cleanFluff(post.seo.metaDescription);
  }
  if (post.faq) {
    post.faq = post.faq.map(f => ({
      question: cleanFluff(f.question),
      answer: cleanFluff(f.answer)
    }));
  }
  if (post.metrics) {
    post.metrics = post.metrics.map(m => ({
      ...m,
      description: cleanFluff(m.description)
    }));
  }
  if (post.expertTip) {
    post.expertTip.content = cleanFluff(post.expertTip.content);
  }

  // Create formatting for a discrete .ts file
  let slugFolder = 'grants'; // Default
  if (post.category === 'Industry-Specific') slugFolder = 'industry-specific';
  if (post.category === 'Federal Grants') slugFolder = 'federal';
  if (post.category === 'State & Local') slugFolder = 'state-local';
  if (post.category === 'Startup & Seed') slugFolder = 'startup-seed';

  const dirPath = path.join(__dirname, 'lib', 'data', 'blog-posts', slugFolder);
  if (!fs.existsSync(dirPath)) {
    fs.mkdirSync(dirPath, { recursive: true });
  }

  const filePath = path.join(dirPath, `${post.slug}.ts`);
  
  const contentStr = `import { BlogPost } from "@/lib/types";

export const post: BlogPost = ${JSON.stringify(post, null, 2)};

export default post;
`;

  // Fix JSON stringified quotes for exact string matching if needed, though Next.js doesn't care.
  
  fs.writeFileSync(filePath, contentStr, 'utf8');
  console.log(`Extracted and cleaned: ${post.slug} -> ${filePath}`);
  extractedCount++;
}

console.log(`Successfully extracted ${extractedCount} posts. Now you should remove them from blogPosts.ts manually and add imports.`);
